title: Dr. Anand Pal
description: Associate Professor of Physics, Specializing in Quantum Technologies & Global Higher Education
url: "https://anandpal-in.github.io"
baseurl: ""
permalink: pretty
markdown: kramdown
